# Generated by Django 5.2.5 on 2025-09-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('db_name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('suspendido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ['nombre'],
            },
        ),
    ]
