#!/bin/bash

# Script de despliegue manual para Hostinger VPS
# Ejecutar comando por comando en el servidor

echo "🚀 Despliegue Manual de Directiva Agrícola en Hostinger VPS"
echo "IP del servidor: 89.116.51.217"
echo ""

echo "📋 PASO 1: Conectar al servidor"
echo "Ejecuta: ssh root@89.116.51.217"
echo ""

echo "📋 PASO 2: Actualizar sistema"
echo "apt update && apt upgrade -y"
echo ""

echo "📋 PASO 3: Instalar dependencias"
echo "apt install -y python3 python3-pip python3-venv python3-dev nginx mysql-server mysql-client git curl wget unzip libmysqlclient-dev pkg-config redis-server supervisor certbot python3-certbot-nginx"
echo ""

echo "📋 PASO 4: Configurar MySQL"
echo "mysql_secure_installation"
echo "mysql -e \"CREATE DATABASE IF NOT EXISTS directiva_agricola CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\""
echo "mysql -e \"CREATE USER IF NOT EXISTS 'directiva_user'@'localhost' IDENTIFIED BY 'Directiva2024!';\""
echo "mysql -e \"GRANT ALL PRIVILEGES ON directiva_agricola.* TO 'directiva_user'@'localhost';\""
echo "mysql -e \"FLUSH PRIVILEGES;\""
echo ""

echo "📋 PASO 5: Crear directorio del proyecto"
echo "mkdir -p /var/www/directiva_agricola"
echo "cd /var/www/directiva_agricola"
echo ""

echo "📋 PASO 6: Subir archivos del proyecto"
echo "Opción A - Usar SCP desde tu Mac:"
echo "scp -i ~/.ssh/hostinger_key -r /Users/josemanuelbarba/Documents/Directiva\\ Proyectos/DirectivaAgricola/* root@89.116.51.217:/var/www/directiva_agricola/"
echo ""
echo "Opción B - Usar Git (si tienes repositorio):"
echo "git clone https://github.com/tu-usuario/DirectivaAgricola.git ."
echo ""

echo "📋 PASO 7: Crear entorno virtual e instalar dependencias"
echo "python3 -m venv venv"
echo "source venv/bin/activate"
echo "pip install --upgrade pip"
echo "pip install -r requirements.txt"
echo "pip install gunicorn mysqlclient"
echo ""

echo "📋 PASO 8: Configurar variables de entorno"
echo "cat > .env << 'EOF'"
echo "SECRET_KEY=$(python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')"
echo "DEBUG=False"
echo "DB_NAME=directiva_agricola"
echo "DB_USER=directiva_user"
echo "DB_PASSWORD=Directiva2024!"
echo "DB_HOST=localhost"
echo "DB_PORT=3306"
echo "EMAIL_HOST=smtp.hostinger.com"
echo "EMAIL_PORT=587"
echo "EMAIL_HOST_USER=tu_email@tu-dominio.com"
echo "EMAIL_HOST_PASSWORD=tu_password_email"
echo "DEFAULT_FROM_EMAIL=noreply@89.116.51.217"
echo "EOF"
echo ""

echo "📋 PASO 9: Ejecutar migraciones"
echo "python manage.py migrate --settings=directiva_agricola.settings_production"
echo ""

echo "📋 PASO 10: Recopilar archivos estáticos"
echo "python manage.py collectstatic --noinput --settings=directiva_agricola.settings_production"
echo ""

echo "📋 PASO 11: Crear superusuario"
echo "python manage.py createsuperuser --settings=directiva_agricola.settings_production"
echo ""

echo "📋 PASO 12: Configurar permisos"
echo "chown -R www-data:www-data /var/www/directiva_agricola"
echo "chmod -R 755 /var/www/directiva_agricola"
echo ""

echo "📋 PASO 13: Configurar Gunicorn"
echo "cat > /etc/systemd/system/directiva-agricola.service << 'EOF'"
echo "[Unit]"
echo "Description=Directiva Agrícola Gunicorn daemon"
echo "After=network.target"
echo ""
echo "[Service]"
echo "User=www-data"
echo "Group=www-data"
echo "WorkingDirectory=/var/www/directiva_agricola"
echo "Environment=\"PATH=/var/www/directiva_agricola/venv/bin\""
echo "ExecStart=/var/www/directiva_agricola/venv/bin/gunicorn --workers 3 --bind unix:/var/www/directiva_agricola/directiva_agricola.sock directiva_agricola.wsgi:application"
echo "ExecReload=/bin/kill -s HUP \$MAINPID"
echo "Restart=on-failure"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo "EOF"
echo ""

echo "📋 PASO 14: Configurar Nginx"
echo "cat > /etc/nginx/sites-available/directiva_agricola << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name 89.116.51.217;"
echo ""
echo "    location /static/ {"
echo "        alias /var/www/directiva_agricola/static/;"
echo "        expires 30d;"
echo "        add_header Cache-Control \"public, immutable\";"
echo "    }"
echo "    "
echo "    location /media/ {"
echo "        alias /var/www/directiva_agricola/media/;"
echo "        expires 30d;"
echo "        add_header Cache-Control \"public, immutable\";"
echo "    }"
echo ""
echo "    location / {"
echo "        include proxy_params;"
echo "        proxy_pass http://unix:/var/www/directiva_agricola/directiva_agricola.sock;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "    }"
echo "}"
echo "EOF"
echo ""

echo "📋 PASO 15: Habilitar sitio y reiniciar servicios"
echo "ln -s /etc/nginx/sites-available/directiva_agricola /etc/nginx/sites-enabled/"
echo "rm -f /etc/nginx/sites-enabled/default"
echo "nginx -t"
echo "systemctl daemon-reload"
echo "systemctl enable directiva-agricola"
echo "systemctl start directiva-agricola"
echo "systemctl restart nginx"
echo ""

echo "✅ ¡Despliegue completado!"
echo "🌐 Tu aplicación estará disponible en: http://89.116.51.217"
echo ""
echo "📊 Comandos útiles:"
echo "- Ver estado: systemctl status directiva-agricola"
echo "- Ver logs: journalctl -u directiva-agricola -f"
echo "- Reiniciar: systemctl restart directiva-agricola"
