# Generated by Django 5.2 on 2025-09-02 19:54

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del régimen fiscal según el SAT', max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción del régimen fiscal', max_length=200, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el régimen fiscal está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Régimen Fiscal',
                'verbose_name_plural': 'Regímenes Fiscales',
                'db_table': 'regimen_fiscal',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('razon_social', models.CharField(help_text='Nombre completo o razón social del cliente', max_length=200, verbose_name='Razón Social')),
                ('codigo_postal', models.CharField(help_text='Código postal de 5 dígitos', max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe tener exactamente 5 dígitos', regex='^\\d{5}$')], verbose_name='Código Postal')),
                ('rfc', models.CharField(help_text='Registro Federal de Contribuyentes (12 o 13 caracteres)', max_length=13, unique=True, validators=[core.models.validar_rfc], verbose_name='RFC')),
                ('domicilio', models.TextField(help_text='Dirección completa del cliente', verbose_name='Domicilio')),
                ('telefono', models.CharField(help_text='Número de teléfono del cliente', max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números, espacios, guiones, paréntesis y el signo más', regex='^[\\d\\s\\-\\+\\(\\)]+$')], verbose_name='Teléfono')),
                ('email_principal', models.EmailField(help_text='Correo electrónico principal del cliente', max_length=254, verbose_name='Correo Electrónico Principal')),
                ('email_alterno', models.EmailField(blank=True, help_text='Correo electrónico alternativo del cliente (opcional)', max_length=254, null=True, verbose_name='Correo Electrónico Alterno')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
                ('regimen_fiscal', models.ForeignKey(help_text='Régimen fiscal del cliente según el SAT', on_delete=django.db.models.deletion.PROTECT, to='core.regimenfiscal', verbose_name='Régimen Fiscal')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['rfc'], name='clientes_rfc_48375a_idx'), models.Index(fields=['razon_social'], name='clientes_razon_s_6d1478_idx'), models.Index(fields=['activo'], name='clientes_activo_1f6d14_idx')],
            },
        ),
    ]
