# Generated by Django 5.2 on 2025-09-02 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_regimenfiscal_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad del cliente (opcional)', max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega',
            field=models.TextField(blank=True, help_text='Dirección específica para entregas (opcional)', null=True, verbose_name='Dirección de Entrega'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado del cliente (opcional)', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_bodega',
            field=models.CharField(blank=True, help_text='Número o identificador de la bodega (opcional)', max_length=50, null=True, verbose_name='Número de Bodega'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_bodega',
            field=models.CharField(blank=True, help_text='Número de teléfono de la bodega (opcional)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números, espacios, guiones, paréntesis y el signo más', regex='^[\\d\\s\\-\\+\\(\\)]+$')], verbose_name='Teléfono de Bodega'),
        ),
    ]
