# Generated by Django 5.2 on 2025-09-02 21:15

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_ciudad_cliente_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre completo o razón social del proveedor', max_length=200, verbose_name='Nombre')),
                ('rfc', models.CharField(help_text='Registro Federal de Contribuyentes (12 o 13 caracteres)', max_length=13, unique=True, validators=[core.models.validar_rfc], verbose_name='RFC')),
                ('domicilio', models.TextField(help_text='Dirección completa del proveedor', verbose_name='Domicilio')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el proveedor está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['rfc'], name='proveedores_rfc_669982_idx'), models.Index(fields=['nombre'], name='proveedores_nombre_4e7949_idx'), models.Index(fields=['activo'], name='proveedores_activo_068092_idx')],
            },
        ),
    ]
