# Generated by Django 5.2 on 2025-09-02 21:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del transportista', max_length=200, verbose_name='Nombre Completo')),
                ('licencia', models.CharField(help_text='Número de licencia de conducir', max_length=50, verbose_name='Licencia')),
                ('domicilio', models.TextField(help_text='Dirección completa del transportista', verbose_name='Domicilio')),
                ('telefono', models.CharField(help_text='Número de teléfono del transportista', max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números, espacios, guiones, paréntesis y el signo más', regex='^[\\d\\s\\-\\+\\(\\)]+$')], verbose_name='Teléfono')),
                ('tipo_camion', models.CharField(help_text='Tipo o modelo del camión', max_length=100, verbose_name='Tipo de Camión')),
                ('placas_unidad', models.CharField(help_text='Placas del camión principal', max_length=20, verbose_name='Placas de Unidad')),
                ('placas_remolque', models.CharField(blank=True, help_text='Placas del remolque (opcional)', max_length=20, null=True, verbose_name='Placas de Remolque')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el transportista está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportistas_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportistas_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'transportistas',
                'ordering': ['nombre_completo'],
                'indexes': [models.Index(fields=['licencia'], name='transportis_licenci_0fe8ad_idx'), models.Index(fields=['nombre_completo'], name='transportis_nombre__130c80_idx'), models.Index(fields=['placas_unidad'], name='transportis_placas__61e3be_idx'), models.Index(fields=['activo'], name='transportis_activo_f2c8fb_idx')],
            },
        ),
    ]
