# Generated by Django 5.2 on 2025-09-02 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transportista'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteOrigen',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre del lote de origen', max_length=200, verbose_name='Nombre')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el lote de origen', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el lote de origen está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_origen_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_origen_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
            ],
            options={
                'verbose_name': 'Lote de Origen',
                'verbose_name_plural': 'Lotes de Origen',
                'db_table': 'lotes_origen',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='lotes_orige_nombre_8131b3_idx'), models.Index(fields=['activo'], name='lotes_orige_activo_ad30f3_idx')],
            },
        ),
    ]
