# Generated by Django 5.2 on 2025-09-02 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loteorigen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionGasto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción de la clasificación de gasto', max_length=200, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la clasificación de gasto', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la clasificación de gasto está activa en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones_gasto_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones_gasto_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
            ],
            options={
                'verbose_name': 'Clasificación de Gasto',
                'verbose_name_plural': 'Clasificaciones de Gastos',
                'db_table': 'clasificaciones_gasto',
                'ordering': ['descripcion'],
                'indexes': [models.Index(fields=['descripcion'], name='clasificaci_descrip_e92818_idx'), models.Index(fields=['activo'], name='clasificaci_activo_4e8b21_idx')],
            },
        ),
    ]
