# Generated by Django 5.2 on 2025-09-02 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clasificaciongasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción del centro de costo', max_length=200, verbose_name='Descripción')),
                ('hectareas', models.DecimalField(decimal_places=2, help_text='Número de hectáreas del centro de costo', max_digits=10, verbose_name='Hectáreas')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el centro de costo', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el centro de costo está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_costo_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_costo_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costos',
                'db_table': 'centros_costo',
                'ordering': ['descripcion'],
                'indexes': [models.Index(fields=['descripcion'], name='centros_cos_descrip_3af6a8_idx'), models.Index(fields=['activo'], name='centros_cos_activo_4ca146_idx')],
            },
        ),
    ]
