# Generated by Django 5.2 on 2025-09-02 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_centrocosto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('sku', models.CharField(help_text='Clave alfanumérica única del producto o servicio', max_length=50, unique=True, verbose_name='SKU')),
                ('descripcion', models.CharField(help_text='Descripción del producto o servicio', max_length=200, verbose_name='Descripción')),
                ('producto_servicio', models.BooleanField(default=True, help_text='True = Producto, False = Servicio', verbose_name='Tipo')),
                ('unidad_medida', models.CharField(help_text='Unidad de medida según catálogo SAT', max_length=10, verbose_name='Unidad de Medida')),
                ('clave_sat', models.CharField(help_text='Clave del catálogo ClaveProdServ del SAT', max_length=20, verbose_name='Clave SAT')),
                ('impuesto', models.CharField(choices=[('IVA_16', 'IVA Tasa 16%'), ('IVA_0', 'IVA Tasa cero'), ('IVA_EXENTO', 'IVA exento')], help_text='Tipo de impuesto aplicable', max_length=20, verbose_name='Impuesto')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto o servicio está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_servicios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_servicios_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
            ],
            options={
                'verbose_name': 'Producto o Servicio',
                'verbose_name_plural': 'Productos y Servicios',
                'db_table': 'productos_servicios',
                'ordering': ['descripcion'],
                'indexes': [models.Index(fields=['sku'], name='productos_s_sku_ddc93a_idx'), models.Index(fields=['descripcion'], name='productos_s_descrip_3d9234_idx'), models.Index(fields=['producto_servicio'], name='productos_s_product_fa5ceb_idx'), models.Index(fields=['clave_sat'], name='productos_s_clave_s_83ebe6_idx'), models.Index(fields=['activo'], name='productos_s_activo_d0202b_idx')],
            },
        ),
    ]
