# Generated by Django 5.2 on 2025-09-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productoservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='unidad_medida',
            field=models.CharField(help_text='Unidad de medida del producto o servicio', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
