# Generated by Django 5.2 on 2025-09-03 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_productoservicio_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_actual', models.CharField(help_text='Nombre del ciclo de producción actual', max_length=100, verbose_name='Ciclo actual')),
                ('nombre_pac', models.CharField(choices=[('PRODIGIA', 'Prodigia')], default='PRODIGIA', help_text='Proveedor Autorizado de Certificación', max_length=50, verbose_name='Nombre de PAC')),
                ('contrato', models.CharField(help_text='Número de contrato con el PAC', max_length=100, verbose_name='Contrato')),
                ('usuario_pac', models.CharField(help_text='Usuario para el PAC', max_length=100, verbose_name='Usuario')),
                ('password_pac', models.CharField(help_text='Contraseña para el PAC', max_length=100, verbose_name='Contraseña')),
                ('certificado', models.TextField(blank=True, help_text='Certificado en formato base64', null=True, verbose_name='Certificado')),
                ('llave', models.TextField(blank=True, help_text='Llave privada en formato base64', null=True, verbose_name='Llave')),
                ('password_llave', models.CharField(blank=True, help_text='Contraseña para la llave privada', max_length=100, verbose_name='Contraseña de la llave')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de modificación')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
    ]
