# Generated by Django 5.2 on 2025-09-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuracionsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ciclo_actual',
            field=models.CharField(blank=True, help_text='Nombre del ciclo de producción actual', max_length=100, verbose_name='Ciclo actual'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='contrato',
            field=models.CharField(blank=True, help_text='Número de contrato con el PAC', max_length=100, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='password_pac',
            field=models.CharField(blank=True, help_text='Contraseña para el PAC', max_length=100, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='usuario_pac',
            field=models.CharField(blank=True, help_text='Usuario para el PAC', max_length=100, verbose_name='Usuario'),
        ),
    ]
