# Generated by Django 5.2 on 2025-09-03 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_configuracionsistema_ciclo_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre del cultivo', max_length=100, verbose_name='Nombre del cultivo')),
                ('variedad', models.CharField(help_text='Variedad del cultivo', max_length=100, verbose_name='Variedad')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cultivo está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de modificación')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'db_table': 'cultivos',
                'ordering': ['nombre', 'variedad'],
            },
        ),
    ]
