# Generated by Django 5.2 on 2025-09-03 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cultivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de modificación'),
        ),
    ]
