# Generated by Django 5.2 on 2025-09-03 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cultivo_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('ciclo', models.CharField(help_text='Ciclo de producción actual', max_length=100, verbose_name='Ciclo')),
                ('folio', models.PositiveIntegerField(help_text='Número de folio de la remisión', verbose_name='Folio')),
                ('fecha', models.DateField(help_text='Fecha de la remisión', verbose_name='Fecha')),
                ('costo_flete', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo del flete de transporte', max_digits=10, verbose_name='Costo de Flete')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la remisión', null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('cliente', models.ForeignKey(help_text='Cliente de la remisión', on_delete=django.db.models.deletion.PROTECT, to='core.cliente', verbose_name='Cliente')),
                ('lote_origen', models.ForeignKey(help_text='Lote de origen de la remisión', on_delete=django.db.models.deletion.PROTECT, to='core.loteorigen', verbose_name='Lote - Origen')),
                ('transportista', models.ForeignKey(help_text='Transportista de la remisión', on_delete=django.db.models.deletion.PROTECT, to='core.transportista', verbose_name='Transportista')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
            ],
            options={
                'verbose_name': 'Remisión',
                'verbose_name_plural': 'Remisiones',
                'db_table': 'remisiones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RemisionDetalle',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('calidad', models.CharField(choices=[('1ras/2das', '1ras/2das'), ('3as', '3as'), ('4as', '4as'), ('Mixtas', 'Mixtas')], help_text='Calidad del producto', max_length=20, verbose_name='Calidad')),
                ('no_arps', models.PositiveIntegerField(help_text='Número de arps', verbose_name='No Arps')),
                ('kgs_enviados', models.DecimalField(decimal_places=2, help_text='Kilogramos enviados', max_digits=10, verbose_name='Kgs Enviados')),
                ('merma_arps', models.PositiveIntegerField(help_text='Merma por arps', verbose_name='Merma/Arps')),
                ('peso_promedio', models.DecimalField(decimal_places=2, help_text='Peso promedio calculado automáticamente', max_digits=10, verbose_name='Peso Promedio')),
                ('kgs_liquidados', models.DecimalField(decimal_places=2, default=0.0, help_text='Kilogramos liquidados', max_digits=10, verbose_name='Kgs Liquidados')),
                ('kgs_merma', models.DecimalField(decimal_places=2, default=0.0, help_text='Kilogramos de merma', max_digits=10, verbose_name='Kgs Merma')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio por kilogramo', max_digits=10, verbose_name='Precio')),
                ('importe_liquidado', models.DecimalField(decimal_places=2, default=0.0, help_text='Importe total liquidado', max_digits=12, verbose_name='Importe Liquidado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('cultivo', models.ForeignKey(help_text='Cultivo del detalle', on_delete=django.db.models.deletion.PROTECT, to='core.cultivo', verbose_name='Cultivo')),
                ('remision', models.ForeignKey(help_text='Remisión a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.remision', verbose_name='Remisión')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_detalles_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_detalles_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
            ],
            options={
                'verbose_name': 'Detalle de Remisión',
                'verbose_name_plural': 'Detalles de Remisiones',
                'db_table': 'remisiones_detalles',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['ciclo', 'folio'], name='remisiones_ciclo_d6b184_idx'),
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['fecha'], name='remisiones_fecha_697658_idx'),
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['cliente'], name='remisiones_cliente_eb1548_idx'),
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['lote_origen'], name='remisiones_lote_or_a06442_idx'),
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['transportista'], name='remisiones_transpo_0f0fb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='remision',
            unique_together={('ciclo', 'folio')},
        ),
        migrations.AddIndex(
            model_name='remisiondetalle',
            index=models.Index(fields=['remision'], name='remisiones__remisio_a66c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='remisiondetalle',
            index=models.Index(fields=['cultivo'], name='remisiones__cultivo_637993_idx'),
        ),
        migrations.AddIndex(
            model_name='remisiondetalle',
            index=models.Index(fields=['calidad'], name='remisiones__calidad_f9c377_idx'),
        ),
    ]
