# Generated by Django 5.2 on 2025-09-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remision_remisiondetalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisiondetalle',
            name='peso_promedio',
            field=models.DecimalField(decimal_places=4, help_text='Peso promedio calculado automáticamente', max_digits=15, verbose_name='Peso Promedio'),
        ),
    ]
