# Generated by Django 5.2 on 2025-09-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_increase_decimal_fields_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisiondetalle',
            name='importe_liquidado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Importe total liquidado', max_digits=18, verbose_name='Importe Liquidado'),
        ),
        migrations.AlterField(
            model_name='remisiondetalle',
            name='kgs_enviados',
            field=models.DecimalField(decimal_places=2, help_text='Kilogramos enviados', max_digits=15, verbose_name='Kgs Enviados'),
        ),
        migrations.AlterField(
            model_name='remisiondetalle',
            name='kgs_liquidados',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Kilogramos liquidados', max_digits=15, verbose_name='Kgs Liquidados'),
        ),
        migrations.AlterField(
            model_name='remisiondetalle',
            name='kgs_merma',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Kilogramos de merma', max_digits=15, verbose_name='Kgs Merma'),
        ),
        migrations.AlterField(
            model_name='remisiondetalle',
            name='peso_promedio',
            field=models.DecimalField(decimal_places=2, help_text='Peso promedio calculado automáticamente', max_digits=15, verbose_name='Peso Promedio'),
        ),
        migrations.AlterField(
            model_name='remisiondetalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio por kilogramo', max_digits=15, verbose_name='Precio'),
        ),
    ]
