# Generated by Django 5.2 on 2025-09-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_round_decimal_fields_to_2_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisiondetalle',
            name='peso_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso promedio calculado automáticamente', max_digits=15, verbose_name='Peso Promedio'),
        ),
    ]
