# Generated by Django 5.2 on 2025-09-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_remisiondetalle_peso_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='liquidada',
            field=models.BooleanField(default=False, help_text='Indica si la remisión ha sido liquidada', verbose_name='Liquidada'),
        ),
    ]
