# Generated by Django 5.2 on 2025-09-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remision_liquidada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remision',
            name='liquidada',
        ),
    ]
