# Generated by Django 5.2 on 2025-09-03 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20250903_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisiondetalle',
            name='fecha_liquidacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de liquidación'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='usuario_liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_detalles_liquidadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que liquidó el detalle'),
        ),
    ]
