# Generated by Django 5.2 on 2025-09-03 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remisiondetalle_fecha_liquidacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Remisión cancelada'),
        ),
        migrations.AddField(
            model_name='remision',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación'),
        ),
        migrations.AddField(
            model_name='remision',
            name='folio_sustituto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio que sustituye'),
        ),
        migrations.AddField(
            model_name='remision',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='remision',
            name='usuario_cancelacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que canceló la remisión'),
        ),
    ]
