# Generated by Django 5.2 on 2025-09-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remision_cancelada_remision_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='facturado',
            field=models.BooleanField(default=False, help_text='Indica si la remisión ha sido facturada', verbose_name='Facturado'),
        ),
        migrations.AddField(
            model_name='remision',
            name='pagado',
            field=models.BooleanField(default=False, help_text='Indica si la remisión ha sido pagada', verbose_name='Pagado'),
        ),
    ]
