# Generated by Django 5.2.5 on 2025-09-10 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remision_facturado_remision_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre_banco', models.CharField(help_text='Nombre completo del banco', max_length=200, verbose_name='Nombre del Banco')),
                ('numero_cuenta', models.CharField(help_text='Número de cuenta bancaria', max_length=50, verbose_name='Número de Cuenta')),
                ('nombre_corto', models.CharField(help_text='Nombre corto para identificar la cuenta (ej: BBVA Principal)', max_length=100, verbose_name='Nombre Corto')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la cuenta bancaria está activa en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'cuentas_bancarias',
                'ordering': ['nombre_corto'],
                'indexes': [models.Index(fields=['nombre_banco'], name='cuentas_ban_nombre__304a88_idx'), models.Index(fields=['numero_cuenta'], name='cuentas_ban_numero__a7969b_idx'), models.Index(fields=['nombre_corto'], name='cuentas_ban_nombre__013077_idx'), models.Index(fields=['activo'], name='cuentas_ban_activo_baed7f_idx')],
            },
        ),
    ]
