# Generated by Django 5.2.5 on 2025-09-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cuentabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='certificado_nombre',
            field=models.CharField(blank=True, help_text='Nombre original del archivo de certificado', max_length=255, null=True, verbose_name='Nombre del certificado'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='llave_nombre',
            field=models.CharField(blank=True, help_text='Nombre original del archivo de llave', max_length=255, null=True, verbose_name='Nombre de la llave'),
        ),
    ]
