# Generated by Django 5.2.5 on 2025-09-10 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_configuracionsistema_certificado_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRemision',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], max_length=20, verbose_name='Método de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia/Comprobante')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuentabancaria', verbose_name='Cuenta Bancaria')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.remision', verbose_name='Remisión')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Última Modificación')),
            ],
            options={
                'verbose_name': 'Pago de Remisión',
                'verbose_name_plural': 'Pagos de Remisiones',
                'ordering': ['-fecha_pago', '-fecha_creacion'],
            },
        ),
    ]
