# Generated by Django 5.2.5 on 2025-09-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_pagoremision'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha en que se realizó el pago', null=True, verbose_name='Fecha de Pago'),
        ),
    ]
