# Generated by Django 5.2.5 on 2025-09-10 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remision_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoremision',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cuentabancaria', verbose_name='Cuenta Bancaria'),
        ),
    ]
