# Generated by Django 5.2.5 on 2025-09-10 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_pagoremision_cuenta_bancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoGasto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('ciclo', models.CharField(help_text='Ciclo de producción para el cual se define el presupuesto', max_length=100, verbose_name='Ciclo')),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe presupuestado para esta clasificación de gasto', max_digits=12, verbose_name='Importe')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el presupuesto', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el presupuesto está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('centro_costo', models.ForeignKey(help_text='Centro de costo al que pertenece el presupuesto', on_delete=django.db.models.deletion.PROTECT, to='core.centrocosto', verbose_name='Centro de Costo')),
                ('clasificacion_gasto', models.ForeignKey(help_text='Clasificación de gasto presupuestada', on_delete=django.db.models.deletion.PROTECT, to='core.clasificaciongasto', verbose_name='Clasificación de Gasto')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_gasto_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_gasto_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Última Modificación')),
            ],
            options={
                'verbose_name': 'Presupuesto de Gasto',
                'verbose_name_plural': 'Presupuestos de Gastos',
                'db_table': 'presupuestos_gasto',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['centro_costo', 'ciclo'], name='presupuesto_centro__80c89d_idx'), models.Index(fields=['ciclo'], name='presupuesto_ciclo_1f3f8d_idx'), models.Index(fields=['activo'], name='presupuesto_activo_5a4c84_idx')],
                'unique_together': {('centro_costo', 'clasificacion_gasto', 'ciclo')},
            },
        ),
    ]
