# Generated by Django 5.2.5 on 2025-09-10 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_presupuesto_gasto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuestogasto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Presupuesto de Gasto (DEPRECATED)', 'verbose_name_plural': 'Presupuestos de Gastos (DEPRECATED)'},
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('ciclo', models.CharField(help_text='Ciclo de producción para el cual se define el presupuesto', max_length=100, verbose_name='Ciclo')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el presupuesto', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el presupuesto está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('centro_costo', models.ForeignKey(help_text='Centro de costo al que pertenece el presupuesto', on_delete=django.db.models.deletion.PROTECT, to='core.centrocosto', verbose_name='Centro de Costo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Última Modificación')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuestos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoDetalle',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe presupuestado para esta clasificación de gasto', max_digits=12, verbose_name='Importe')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el detalle está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('clasificacion_gasto', models.ForeignKey(help_text='Clasificación de gasto presupuestada', on_delete=django.db.models.deletion.PROTECT, to='core.clasificaciongasto', verbose_name='Clasificación de Gasto')),
                ('presupuesto', models.ForeignKey(help_text='Presupuesto al que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.presupuesto', verbose_name='Presupuesto')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_detalles_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_detalles_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Última Modificación')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto',
                'verbose_name_plural': 'Detalles de Presupuesto',
                'db_table': 'presupuesto_detalles',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['centro_costo', 'ciclo'], name='presupuesto_centro__b3ca24_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['ciclo'], name='presupuesto_ciclo_178382_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['activo'], name='presupuesto_activo_888055_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together={('centro_costo', 'ciclo')},
        ),
        migrations.AddIndex(
            model_name='presupuestodetalle',
            index=models.Index(fields=['presupuesto'], name='presupuesto_presupu_1b9751_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuestodetalle',
            index=models.Index(fields=['clasificacion_gasto'], name='presupuesto_clasifi_f37f99_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuestodetalle',
            index=models.Index(fields=['activo'], name='presupuesto_activo_4a5ee0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presupuestodetalle',
            unique_together={('presupuesto', 'clasificacion_gasto')},
        ),
    ]
