# Generated by Django 5.2.5 on 2025-09-10 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_presupuestogasto_options_presupuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('ciclo', models.CharField(help_text='Ciclo al que pertenece el gasto', max_length=10, verbose_name='Ciclo')),
                ('fecha_gasto', models.DateField(help_text='Fecha en que se realizó el gasto', verbose_name='Fecha del Gasto')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del gasto', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el gasto está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('presupuesto', models.ForeignKey(help_text='Presupuesto al que pertenece este gasto', on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='core.presupuesto', verbose_name='Presupuesto')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Última Modificación')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'gastos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GastoDetalle',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('factura', models.CharField(help_text='Número de factura del proveedor', max_length=100, verbose_name='Factura')),
                ('concepto', models.CharField(help_text='Concepto o descripción del gasto', max_length=255, verbose_name='Concepto')),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe del gasto', max_digits=12, verbose_name='Importe')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el detalle está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('clasificacion_gasto', models.ForeignKey(help_text='Clasificación de gasto según el presupuesto', on_delete=django.db.models.deletion.PROTECT, to='core.clasificaciongasto', verbose_name='Clasificación de Gasto')),
                ('gasto', models.ForeignKey(help_text='Gasto al que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.gasto', verbose_name='Gasto')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que emitió la factura', on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Proveedor')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gasto_detalles_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gasto_detalles_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Última Modificación')),
            ],
            options={
                'verbose_name': 'Detalle de Gasto',
                'verbose_name_plural': 'Detalles de Gastos',
                'db_table': 'gasto_detalles',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['presupuesto', 'ciclo'], name='gastos_presupu_5346b6_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['fecha_gasto'], name='gastos_fecha_g_cb5346_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['activo'], name='gastos_activo_42870b_idx'),
        ),
        migrations.AddIndex(
            model_name='gastodetalle',
            index=models.Index(fields=['gasto'], name='gasto_detal_gasto_i_0fa69d_idx'),
        ),
        migrations.AddIndex(
            model_name='gastodetalle',
            index=models.Index(fields=['proveedor'], name='gasto_detal_proveed_4e6c40_idx'),
        ),
        migrations.AddIndex(
            model_name='gastodetalle',
            index=models.Index(fields=['factura'], name='gasto_detal_factura_91c7fd_idx'),
        ),
        migrations.AddIndex(
            model_name='gastodetalle',
            index=models.Index(fields=['activo'], name='gasto_detal_activo_c380e1_idx'),
        ),
    ]
