# Generated by Django 5.2.5 on 2025-09-10 23:23

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_gasto_gastodetalle_gasto_gastos_presupu_5346b6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección de la empresa', verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social de la empresa', max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes de la empresa', max_length=13, validators=[core.models.validar_rfc], verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de la empresa', max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números, espacios, guiones, paréntesis y el signo más', regex='^[\\d\\s\\-\\+\\(\\)]+$')], verbose_name='Teléfono'),
        ),
    ]
