# Generated by Django 5.2.5 on 2025-09-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_empresa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='logo_empresa',
            field=models.ImageField(blank=True, help_text='Logotipo de la empresa', null=True, upload_to='logos_empresa/', verbose_name='Logo de la Empresa'),
        ),
    ]
