# Generated by Django 5.2.5 on 2025-09-12 21:14

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_logo_empresa_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('razon_social', models.CharField(help_text='Razón social del emisor', max_length=200, verbose_name='Razón Social')),
                ('rfc', models.CharField(help_text='Registro Federal de Contribuyentes del emisor', max_length=13, validators=[core.models.validar_rfc], verbose_name='RFC')),
                ('codigo_postal', models.CharField(help_text='Código postal de 5 dígitos', max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe tener exactamente 5 dígitos', regex='^\\d{5}$')], verbose_name='Código Postal')),
                ('archivo_certificado', models.FileField(help_text='Archivo .cer del certificado', upload_to='certificados/', verbose_name='Archivo de Certificado')),
                ('archivo_llave', models.FileField(help_text='Archivo .key de la llave privada', upload_to='llaves/', verbose_name='Archivo de Llave')),
                ('password_llave', models.CharField(help_text='Contraseña para la llave privada', max_length=100, verbose_name='Contraseña de la Llave')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el emisor está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emisores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emisores_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Modificación')),
            ],
            options={
                'verbose_name': 'Emisor',
                'verbose_name_plural': 'Emisores',
                'db_table': 'emisores',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['rfc'], name='emisores_rfc_8659b0_idx'), models.Index(fields=['razon_social'], name='emisores_razon_s_d5d49d_idx'), models.Index(fields=['activo'], name='emisores_activo_209d53_idx')],
            },
        ),
    ]
