# Generated by Django 5.2.5 on 2025-09-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_emisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='contrato',
            field=models.CharField(blank=True, help_text='Número de contrato con el PAC', max_length=100, verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='nombre_pac',
            field=models.CharField(choices=[('PRODIGIA', 'Prodigia')], default='PRODIGIA', help_text='Proveedor Autorizado de Certificación', max_length=50, verbose_name='Nombre de PAC'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='password_pac',
            field=models.CharField(blank=True, help_text='Contraseña para el PAC', max_length=100, verbose_name='Contraseña PAC'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='usuario_pac',
            field=models.CharField(blank=True, help_text='Usuario para el PAC', max_length=100, verbose_name='Usuario PAC'),
        ),
    ]
