# Generated by Django 5.2.5 on 2025-09-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_emisor_contrato_emisor_nombre_pac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='timbrado_prueba',
            field=models.BooleanField(default=True, help_text='Indica si el timbrado será en modo prueba o producción', verbose_name='Timbrado de Prueba'),
        ),
    ]
