# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_timbrado_prueba_to_emisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='regimen_fiscal',
            field=models.CharField(
                choices=[
                    ('601', '601 - General de Ley Personas Morales'),
                    ('603', '603 - Personas Morales con Fines no Lucrativos'),
                    ('605', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'),
                    ('606', '606 - Arrendamiento'),
                    ('608', '608 - Demás ingresos'),
                    ('610', '610 - Residentes en el Extranjero sin Establecimiento Permanente en México'),
                    ('611', '611 - Ingresos por Dividendos (socios y accionistas)'),
                    ('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'),
                    ('614', '614 - Ingresos por intereses'),
                    ('615', '615 - Régimen de los ingresos por obtención de premios'),
                    ('616', '616 - Sin obligaciones fiscales'),
                    ('620', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos'),
                    ('621', '621 - Incorporación Fiscal'),
                    ('622', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
                    ('623', '623 - Opcional para Grupos de Sociedades'),
                    ('624', '624 - Coordinados'),
                    ('625', '625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'),
                    ('626', '626 - Régimen Simplificado de Confianza'),
                    ('628', '628 - Hidrocarburos'),
                    ('629', '629 - De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales'),
                    ('630', '630 - Enajenación de acciones en bolsa de valores'),
                ],
                default='626',
                help_text='Régimen fiscal según el SAT',
                max_length=3,
                verbose_name='Régimen Fiscal'
            ),
        ),
    ]
