# Generated by Django 5.2.5 on 2025-09-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_factura_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='serie',
            field=models.CharField(default='A', help_text='Serie para las facturas de este emisor', max_length=10, verbose_name='Serie'),
        ),
    ]
