# Generated by Django 5.2.5 on 2025-09-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_serie_to_emisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cancelada',
            field=models.BooleanField(default=False, help_text='Indica si la factura está cancelada', verbose_name='Cancelada'),
        ),
    ]
