# Generated by Django 5.2.5 on 2025-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_cancelada_to_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='acuse_cancelacion',
            field=models.TextField(blank=True, help_text='Acuse de cancelación del SAT', null=True, verbose_name='Acuse de Cancelación'),
        ),
        migrations.AddField(
            model_name='factura',
            name='errores_validacion',
            field=models.TextField(blank=True, help_text='Errores encontrados en la validación', null=True, verbose_name='Errores de Validación'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado_timbrado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TIMBRADO', 'Timbrado'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error')], default='PENDIENTE', help_text='Estado del timbrado', max_length=20, verbose_name='Estado de Timbrado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de cancelación', null=True, verbose_name='Fecha de Cancelación'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_timbrado',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del timbrado', null=True, verbose_name='Fecha de Timbrado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='intentos_timbrado',
            field=models.PositiveIntegerField(default=0, help_text='Número de intentos de timbrado', verbose_name='Intentos de Timbrado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, help_text='Motivo de la cancelación', max_length=500, null=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AddField(
            model_name='factura',
            name='no_cert_sat',
            field=models.CharField(blank=True, help_text='Número de certificado del SAT', max_length=20, null=True, verbose_name='No. Certificado SAT'),
        ),
        migrations.AddField(
            model_name='factura',
            name='sello_sat',
            field=models.TextField(blank=True, help_text='Sello digital del SAT', null=True, verbose_name='Sello SAT'),
        ),
        migrations.AddField(
            model_name='factura',
            name='ultimo_intento',
            field=models.DateTimeField(blank=True, help_text='Fecha del último intento de timbrado', null=True, verbose_name='Último Intento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='uuid',
            field=models.CharField(blank=True, help_text='UUID del comprobante fiscal', max_length=36, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='factura',
            name='xml_original',
            field=models.TextField(blank=True, help_text='XML original antes del timbrado', null=True, verbose_name='XML Original'),
        ),
        migrations.AddField(
            model_name='factura',
            name='xml_timbrado',
            field=models.TextField(blank=True, help_text='XML timbrado por el PAC', null=True, verbose_name='XML Timbrado'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['uuid'], name='facturas_uuid_a5ed0b_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado_timbrado'], name='facturas_estado__7cb2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_timbrado'], name='facturas_fecha_t_b595d3_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cancelada'], name='facturas_cancela_f63b14_idx'),
        ),
    ]
