# Generated by Django 5.2.6 on 2025-09-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_timbrado_fields_to_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='ultima_actualizacion_catalogos',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última actualización de catálogos SAT', null=True, verbose_name='Última actualización de catálogos'),
        ),
    ]
