# Generated by Django 5.2.6 on 2025-09-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_configuracionsistema_ultima_actualizacion_catalogos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisor',
            name='archivo_certificado',
            field=models.TextField(blank=True, help_text='Archivo .cer del certificado codificado en base64', null=True, verbose_name='Archivo de Certificado (Base64)'),
        ),
        migrations.AlterField(
            model_name='emisor',
            name='archivo_llave',
            field=models.TextField(blank=True, help_text='Archivo .key de la llave privada codificado en base64', null=True, verbose_name='Archivo de Llave (Base64)'),
        ),
    ]
