# Generated by Django 5.2.6 on 2025-09-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_change_certificate_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='nombre_archivo_certificado',
            field=models.CharField(blank=True, help_text='Nombre original del archivo .cer', max_length=255, null=True, verbose_name='Nombre del Archivo de Certificado'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='nombre_archivo_llave',
            field=models.CharField(blank=True, help_text='Nombre original del archivo .key', max_length=255, null=True, verbose_name='Nombre del Archivo de Llave'),
        ),
    ]
