# Generated by Django 5.2.6 on 2025-09-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_nombre_archivos_emisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='impuesto',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Total de impuestos', max_digits=15, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='impuesto_concepto',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Impuesto del concepto', max_digits=15, verbose_name='Impuesto'),
        ),
    ]
