# Generated by Django 5.2.6 on 2025-09-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_fix_decimal_places_impuestos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Factura CFDI 4.0', 'verbose_name_plural': 'Facturas CFDI 4.0'},
        ),
        migrations.AlterModelOptions(
            name='facturadetalle',
            options={'ordering': ['id'], 'verbose_name': 'Concepto CFDI 4.0', 'verbose_name_plural': 'Conceptos CFDI 4.0'},
        ),
        migrations.AddField(
            model_name='factura',
            name='certificado',
            field=models.TextField(blank=True, help_text='Certificado del emisor en Base64', null=True, verbose_name='Certificado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='confirmacion',
            field=models.CharField(blank=True, help_text='Confirmación del comprobante (opcional)', max_length=2, null=True, verbose_name='Confirmacion'),
        ),
        migrations.AddField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Descuento aplicado al comprobante (opcional)', max_digits=15, null=True, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='no_certificado',
            field=models.CharField(blank=True, help_text='Número de serie del certificado del emisor', max_length=20, null=True, verbose_name='NoCertificado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='sello',
            field=models.TextField(blank=True, help_text='Sello digital del comprobante en Base64', null=True, verbose_name='Sello'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_comprobante',
            field=models.CharField(choices=[('I', 'I - Ingreso'), ('E', 'E - Egreso'), ('T', 'T - Traslado'), ('N', 'N - Nómina'), ('P', 'P - Pago')], default='I', help_text='Tipo de comprobante (requerido)', max_length=1, verbose_name='TipoDeComprobante'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='clave_unidad',
            field=models.CharField(default='H87', help_text='Clave de la unidad de medida (requerido)', max_length=3, verbose_name='ClaveUnidad'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Descuento aplicado al concepto (opcional)', max_digits=15, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='exportacion',
            field=models.CharField(choices=[('01', '01 - No aplica'), ('02', '02 - Definitiva'), ('03', '03 - Temporal')], default='01', help_text='Tipo de exportación (requerido)', max_length=2, verbose_name='Exportacion'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(help_text='Fecha y hora de emisión del comprobante (AAAA-MM-DDThh:mm:ss)', verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='folio',
            field=models.AutoField(help_text='Folio consecutivo de la factura (clave primaria)', primary_key=True, serialize=False, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='impuesto',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Total de impuestos trasladados', max_digits=15, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='no_cert_sat',
            field=models.CharField(blank=True, help_text='Número de serie del certificado SAT (20 posiciones)', max_length=20, null=True, verbose_name='NoCertificadoSAT'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sello_sat',
            field=models.TextField(blank=True, help_text='Sello digital del SAT en Base64', null=True, verbose_name='SelloSAT'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='serie',
            field=models.CharField(blank=True, help_text='Serie para control interno del contribuyente (opcional)', max_length=25, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Subtotal del comprobante (requerido)', max_digits=15, verbose_name='SubTotal'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total del comprobante (requerido)', max_digits=15, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='uuid',
            field=models.CharField(blank=True, help_text='UUID del comprobante fiscal timbrado', max_length=36, null=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=6, help_text='Cantidad del producto (requerido)', max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='clave_prod_serv',
            field=models.CharField(help_text='Clave del producto o servicio (requerido)', max_length=20, verbose_name='ClaveProdServ'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='concepto',
            field=models.CharField(help_text='Descripción del concepto (requerido)', max_length=1000, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='importe',
            field=models.DecimalField(decimal_places=2, help_text='Importe del concepto (cantidad * precio) (requerido)', max_digits=15, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='no_identificacion',
            field=models.CharField(blank=True, help_text='Número de identificación del producto (opcional)', max_length=50, null=True, verbose_name='NoIdentificacion'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='objeto_impuesto',
            field=models.CharField(choices=[('01', '01 - No objeto del impuesto'), ('02', '02 - Sí objeto del impuesto'), ('03', '03 - Sí objeto del impuesto y no obligado al desglose')], default='02', help_text='Objeto del impuesto (requerido)', max_length=2, verbose_name='ObjetoImp'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='precio',
            field=models.DecimalField(decimal_places=6, help_text='Valor unitario del producto (requerido)', max_digits=15, verbose_name='ValorUnitario'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='unidad',
            field=models.CharField(default='Pieza', help_text='Unidad de medida (requerido)', max_length=20, verbose_name='Unidad'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['tipo_comprobante'], name='facturas_tipo_co_fe100c_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['exportacion'], name='facturas_exporta_a41794_idx'),
        ),
        migrations.AddIndex(
            model_name='facturadetalle',
            index=models.Index(fields=['factura'], name='factura_det_factura_81d21b_idx'),
        ),
        migrations.AddIndex(
            model_name='facturadetalle',
            index=models.Index(fields=['clave_prod_serv'], name='factura_det_clave_p_b2a196_idx'),
        ),
        migrations.AddIndex(
            model_name='facturadetalle',
            index=models.Index(fields=['objeto_impuesto'], name='factura_det_objeto__f48559_idx'),
        ),
    ]
