# Generated by Django 5.2.6 on 2025-09-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_cfdi_4_0_anexo_20_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=6, help_text='Cantidad del producto (requerido)', max_digits=15, verbose_name='Cantidad'),
        ),
    ]
