# Generated by Django 5.2.6 on 2025-09-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_fix_cantidad_max_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='Descuento aplicado al comprobante (opcional)', max_digits=15, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, help_text='Subtotal del comprobante (requerido)', max_digits=15, verbose_name='SubTotal'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=4, help_text='Total del comprobante (requerido)', max_digits=15, verbose_name='Total'),
        ),
    ]
