# Generated by Django 5.2.5 on 2025-09-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_update_uso_cfdi_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='año_informacion_global',
            field=models.IntegerField(blank=True, help_text='Año del período de la información global', null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='factura',
            name='meses',
            field=models.CharField(blank=True, choices=[('01', '01 - Enero'), ('02', '02 - Febrero'), ('03', '03 - Marzo'), ('04', '04 - Abril'), ('05', '05 - Mayo'), ('06', '06 - Junio'), ('07', '07 - Julio'), ('08', '08 - Agosto'), ('09', '09 - Septiembre'), ('10', '10 - Octubre'), ('11', '11 - Noviembre'), ('12', '12 - Diciembre')], help_text='Meses del período de la información global', max_length=2, null=True, verbose_name='Meses'),
        ),
        migrations.AddField(
            model_name='factura',
            name='periodicidad',
            field=models.CharField(blank=True, choices=[('01', '01 - Mensual'), ('02', '02 - Bimestral'), ('03', '03 - Trimestral'), ('04', '04 - Cuatrimestral'), ('05', '05 - Semestral'), ('06', '06 - Anual')], help_text='Periodicidad de la información global', max_length=2, null=True, verbose_name='Periodicidad'),
        ),
    ]
