# Generated by Django 5.2.5 on 2025-09-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_informacion_global_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='codigo_qr',
            field=models.TextField(blank=True, help_text='Código QR de la factura en Base64 (proporcionado por el PAC)', null=True, verbose_name='Código QR'),
        ),
    ]
