# Generated by Django 5.2.5 on 2025-09-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_codigo_qr_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cadena_original_sat',
            field=models.TextField(blank=True, help_text='Cadena original del complemento SAT (SelloCFD del timbre fiscal)', null=True, verbose_name='Cadena Original complemento SAT'),
        ),
    ]
