# Generated by Django 5.2.5 on 2025-09-19 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_add_cadena_original_sat_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del pago', verbose_name='Fecha de Pago')),
                ('monto_pago', models.DecimalField(decimal_places=2, help_text='Monto pagado en esta transacción', max_digits=15, verbose_name='Monto del Pago')),
                ('tipo_pago', models.CharField(choices=[('PARCIAL', 'Pago Parcial'), ('COMPLETO', 'Pago Completo'), ('ABONO', 'Abono a Cuenta')], default='PARCIAL', help_text='Tipo de pago realizado', max_length=10, verbose_name='Tipo de Pago')),
                ('referencia_pago', models.CharField(blank=True, help_text='Referencia bancaria, transferencia, etc.', max_length=100, null=True, verbose_name='Referencia de Pago')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del pago', null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('factura', models.ForeignKey(help_text='Factura a la que corresponde el pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.factura', verbose_name='Factura')),
                ('usuario_registro', models.ForeignKey(help_text='Usuario que registró el pago', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Pago de Factura',
                'verbose_name_plural': 'Pagos de Facturas',
                'db_table': 'pagos_factura',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
