# Generated by Django 5.2.5 on 2025-09-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_pago_factura_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofactura',
            name='fecha_timbrado',
            field=models.CharField(blank=True, help_text='Fecha de timbrado del complemento de pago', max_length=50, null=True, verbose_name='Fecha Timbrado'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='no_certificado_sat',
            field=models.CharField(blank=True, help_text='Número de certificado del SAT', max_length=20, null=True, verbose_name='No. Certificado SAT'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='sello',
            field=models.TextField(blank=True, help_text='Sello del complemento de pago', null=True, verbose_name='Sello CFD'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='sello_sat',
            field=models.TextField(blank=True, help_text='Sello del timbre fiscal digital', null=True, verbose_name='Sello SAT'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='uuid',
            field=models.CharField(blank=True, help_text='UUID del complemento de pago timbrado', max_length=36, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='xml_timbrado',
            field=models.TextField(blank=True, help_text='XML del complemento de pago timbrado en Base64', null=True, verbose_name='XML Timbrado'),
        ),
    ]
