# Generated by Django 5.2.5 on 2025-09-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_add_timbrado_fields_to_pago_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofactura',
            name='num_parcialidad',
            field=models.PositiveIntegerField(default=1, help_text='Número de parcialidad del pago', verbose_name='Número de Parcialidad'),
        ),
    ]
