# Generated by Django 5.2.5 on 2025-09-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_pagofactura_num_parcialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofactura',
            name='forma_pago',
            field=models.CharField(default='03', help_text='Código de forma de pago según catálogo SAT', max_length=2, verbose_name='Forma de Pago'),
        ),
    ]
