# Generated by Django 5.2.5 on 2025-09-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_pagofactura_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofactura',
            name='cadena_original_sat',
            field=models.TextField(blank=True, help_text='Cadena original del complemento SAT (SelloCFD del timbre fiscal)', null=True, verbose_name='Cadena Original complemento SAT'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='codigo_qr',
            field=models.TextField(blank=True, help_text='Código QR del complemento de pago en Base64', null=True, verbose_name='Código QR'),
        ),
    ]
