# Generated by Django 5.2.5 on 2025-10-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_pagofactura_cadena_original_sat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='merma_arps_global',
            field=models.PositiveIntegerField(default=0, help_text='Número total de arps con merma en la remisión', verbose_name='Merma/Arps Global'),
        ),
        migrations.AddField(
            model_name='remision',
            name='peso_bruto_embarque',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso total bruto de la remisión en kilogramos', max_digits=15, verbose_name='Peso Bruto de Embarque'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='importe_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Importe total de envío (Precio Envío × Kgs Enviados)', max_digits=18, verbose_name='Importe Envío'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='importe_neto_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Importe neto de envío (Precio Envío × Kgs Neto Envío)', max_digits=18, verbose_name='Importe Neto Envío'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='kgs_neto_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Kilogramos netos de envío (Kgs Enviados - Kgs Merma)', max_digits=15, verbose_name='Kgs Neto Envío'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='precio_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio por kilogramo para envío', max_digits=15, verbose_name='Precio Envío'),
        ),
    ]
