# Generated by Django 5.2.5 on 2025-10-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_pagofactura_cadena_original_sat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='impuesto',
            field=models.CharField(choices=[('IVA_16', 'IVA Tasa 16%'), ('IVA_0', 'IVA Tasa cero'), ('IVA_EXENTO', 'IVA exento')], help_text='Tipo de impuesto aplicable (legado). Se usará el catálogo si está asignado.', max_length=20, verbose_name='Impuesto'),
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del SAT (ej. 002 para IVA)', max_length=3, verbose_name='Código SAT')),
                ('nombre', models.CharField(help_text='Nombre del impuesto (ej. IVA Tasa 16%)', max_length=100, verbose_name='Nombre')),
                ('tasa', models.DecimalField(decimal_places=4, help_text='Tasa decimal (ej. 0.1600 para 16%)', max_digits=6, verbose_name='Tasa')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'tipo_impuesto',
                'ordering': ['codigo', 'tasa'],
                'indexes': [models.Index(fields=['codigo'], name='tipo_impues_codigo_c1e920_idx'), models.Index(fields=['activo'], name='tipo_impues_activo_b7211f_idx')],
            },
        ),
        migrations.AddField(
            model_name='productoservicio',
            name='impuesto_catalogo',
            field=models.ForeignKey(blank=True, help_text='Impuesto desde catálogo', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.impuesto', verbose_name='Impuesto (catálogo)'),
        ),
    ]
