# Generated by Django 5.2.5 on 2025-10-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_remision_envio_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='merma_arps_liquidados',
            field=models.PositiveIntegerField(default=0, help_text='Número de arps con merma liquidados', verbose_name='Merma/Arps Liquidados'),
        ),
        migrations.AddField(
            model_name='remision',
            name='peso_bruto_liquidado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso bruto liquidado en kilogramos', max_digits=15, verbose_name='Peso Bruto Liquidado'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='no_arps_liquidados',
            field=models.PositiveIntegerField(default=0, help_text='Número de arps liquidados', verbose_name='No Arps Liquidados'),
        ),
    ]
