# Generated by Django 5.2.5 on 2025-10-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_add_liquidation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisiondetalle',
            name='kgs_merma_liquidados',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Kilogramos de merma liquidados', max_digits=15, verbose_name='Kgs Merma Liquidados'),
        ),
    ]
