# Generated by Django 5.2.5 on 2025-10-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_add_kgs_merma_liquidados_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisiondetalle',
            name='peso_promedio_liquidado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso promedio liquidado calculado automáticamente', max_digits=15, verbose_name='Peso Promedio Liquidado'),
        ),
    ]
