# Generated by Django 5.2.5 on 2025-10-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_add_peso_promedio_liquidado_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisiondetalle',
            name='dif_importes',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Diferencia entre Importe Neto Envío e Importe Liquidado', max_digits=18, verbose_name='Dif Importes'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='dif_kgs_liquidados',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Diferencia entre Kgs Enviados y Kgs Liquidados', max_digits=15, verbose_name='Dif Kgs Liquidados'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='dif_kgs_merma',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Diferencia entre Kgs Merma y Kgs Merma Liquidados', max_digits=15, verbose_name='Dif Kgs Merma'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='dif_no_arps',
            field=models.IntegerField(default=0, help_text='Diferencia entre No Arps y No Arps Liquidados', verbose_name='Dif No Arps'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='dif_peso_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Diferencia entre Peso Promedio y Peso Promedio Liquidado', max_digits=15, verbose_name='Dif Peso Promedio'),
        ),
        migrations.AddField(
            model_name='remisiondetalle',
            name='dif_precio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Diferencia entre Precio Envío y Precio por Kg', max_digits=15, verbose_name='Dif Precio'),
        ),
    ]
