# Generated by Django 5.2.5 on 2025-10-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_add_difference_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo de la persona que autoriza gastos', max_length=200, verbose_name='Nombre completo')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la persona está activa para autorizar gastos', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Autorizó Gasto',
                'verbose_name_plural': 'Autorizó Gastos',
                'db_table': 'autorizo_gasto',
                'ordering': ['nombre'],
            },
        ),
    ]
