# Generated by Django 5.2.5 on 2025-10-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_gastodetalle_autorizo_gastodetalle_forma_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción del almacén', max_length=200, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el almacén está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacenes',
                'ordering': ['descripcion'],
            },
        ),
    ]
