# Generated by Django 5.2.5 on 2025-10-14 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_create_almacen_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False, verbose_name='Folio')),
                ('fecha', models.DateField(help_text='Fecha en que se realizó la compra', verbose_name='Fecha de compra')),
                ('factura', models.CharField(blank=True, help_text='Número de factura del proveedor', max_length=50, null=True, verbose_name='Factura')),
                ('serie', models.CharField(blank=True, help_text='Serie de la factura', max_length=20, null=True, verbose_name='Serie')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal de la compra', max_digits=12, verbose_name='Subtotal')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, help_text='Impuestos de la compra', max_digits=12, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total de la compra', max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado de la compra', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('proveedor', models.ForeignKey(help_text='Proveedor de la compra', on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['-fecha', '-folio'],
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad comprada', max_digits=10, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del detalle (cantidad × precio)', max_digits=12, verbose_name='Subtotal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('almacen', models.ForeignKey(help_text='Almacén donde se almacenará el producto', on_delete=django.db.models.deletion.PROTECT, to='core.almacen', verbose_name='Almacén')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.compra', verbose_name='Compra')),
                ('producto', models.ForeignKey(help_text='Producto o servicio comprado', on_delete=django.db.models.deletion.PROTECT, to='core.productoservicio', verbose_name='Producto/Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'compra_detalles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del movimiento')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Total')),
                ('existencia_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Existencia Anterior')),
                ('existencia_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Existencia Actual')),
                ('costo_promedio_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Promedio Anterior')),
                ('costo_promedio_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Promedio Actual')),
                ('referencia', models.CharField(blank=True, help_text='Referencia del movimiento (folio de compra, etc.)', max_length=100, null=True, verbose_name='Referencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.almacen', verbose_name='Almacén')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productoservicio', verbose_name='Producto/Servicio')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardex',
                'db_table': 'kardex',
                'ordering': ['-fecha', '-id'],
                'unique_together': {('producto', 'almacen', 'fecha', 'tipo_movimiento')},
            },
        ),
    ]
