# Generated by Django 5.2.5 on 2025-10-16 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_compra_compradetalle_kardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoservicio',
            name='clasificacion_gasto',
            field=models.ForeignKey(blank=True, help_text='Clasificación de gasto para este producto o servicio', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.clasificaciongasto', verbose_name='Clasificación de Gasto'),
        ),
    ]
