# Generated by Django 5.2.5 on 2025-10-17 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_add_clasificacion_gasto_to_producto_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSalida',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción del tipo de salida', max_length=100, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el tipo de salida está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de Salida',
                'verbose_name_plural': 'Tipos de Salida',
                'db_table': 'tipos_salida',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('folio', models.CharField(help_text='Folio único de la salida', max_length=20, unique=True, verbose_name='Folio')),
                ('fecha', models.DateField(help_text='Fecha en que se realiza la salida', verbose_name='Fecha de salida')),
                ('ciclo', models.CharField(help_text='Ciclo de producción actual', max_length=10, verbose_name='Ciclo')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la salida está activa', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('autorizo', models.ForeignKey(help_text='Persona que autoriza la salida', on_delete=django.db.models.deletion.PROTECT, to='core.autorizogasto', verbose_name='Autorizó')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_inventario_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_inventario_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el registro')),
                ('tipo_salida', models.ForeignKey(help_text='Tipo de salida de inventario', on_delete=django.db.models.deletion.PROTECT, to='core.tiposalida', verbose_name='Tipo de salida')),
            ],
            options={
                'verbose_name': 'Salida de Inventario',
                'verbose_name_plural': 'Salidas de Inventario',
                'db_table': 'salidas_inventario',
                'ordering': ['-fecha', '-folio'],
            },
        ),
        migrations.CreateModel(
            name='SalidaInventarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad que se da de salida', max_digits=10, verbose_name='Cantidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('almacen', models.ForeignKey(help_text='Almacén del cual se saca el producto', on_delete=django.db.models.deletion.PROTECT, to='core.almacen', verbose_name='Almacén')),
                ('centro_costo', models.ForeignKey(help_text='Centro de costo al que se asigna la salida', on_delete=django.db.models.deletion.PROTECT, to='core.centrocosto', verbose_name='Centro de Costo')),
                ('producto', models.ForeignKey(help_text='Producto que se está dando de salida', on_delete=django.db.models.deletion.PROTECT, to='core.productoservicio', verbose_name='Producto/Servicio')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.salidainventario', verbose_name='Salida de inventario')),
            ],
            options={
                'verbose_name': 'Detalle de Salida de Inventario',
                'verbose_name_plural': 'Detalles de Salidas de Inventario',
                'db_table': 'salidas_inventario_detalles',
                'ordering': ['id'],
            },
        ),
    ]
