# Generated by Django 5.2.5 on 2025-10-17 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_tiposalida_salidainventario_salidainventariodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastodetalle',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor que emitió la factura', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Proveedor'),
        ),
    ]
