# Generated by Django 5.2.5 on 2025-10-17 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_make_proveedor_optional_in_gastodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtroMovimiento',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False, verbose_name='Folio')),
                ('fecha', models.DateField(verbose_name='Fecha del movimiento')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Otras entradas'), ('salida', 'Otras salidas'), ('traspaso', 'Traspaso entre almacenes')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otros_movimientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación')),
            ],
            options={
                'verbose_name': 'Otro Movimiento',
                'verbose_name_plural': 'Otros Movimientos',
                'db_table': 'otros_movimientos',
                'ordering': ['-fecha', '-folio'],
            },
        ),
        migrations.CreateModel(
            name='OtroMovimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='core.almacen', verbose_name='Almacén de destino')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='core.almacen', verbose_name='Almacén de origen')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.otromovimiento', verbose_name='Movimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productoservicio', verbose_name='Producto/Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Otro Movimiento',
                'verbose_name_plural': 'Detalles de Otros Movimientos',
                'db_table': 'otros_movimientos_detalle',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
