CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "usuarios" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "nombre" varchar(100) NOT NULL, "puesto" varchar(100) NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "is_admin" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "usuarios_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "usuario_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "usuarios_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "usuario_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "usuarios_groups_usuario_id_group_id_a66c5ef3_uniq" ON "usuarios_groups" ("usuario_id", "group_id");
CREATE INDEX "usuarios_groups_usuario_id_1132ca50" ON "usuarios_groups" ("usuario_id");
CREATE INDEX "usuarios_groups_group_id_18c61092" ON "usuarios_groups" ("group_id");
CREATE UNIQUE INDEX "usuarios_user_permissions_usuario_id_permission_id_474b33a5_uniq" ON "usuarios_user_permissions" ("usuario_id", "permission_id");
CREATE INDEX "usuarios_user_permissions_usuario_id_232fd58d" ON "usuarios_user_permissions" ("usuario_id");
CREATE INDEX "usuarios_user_permissions_permission_id_af615ca1" ON "usuarios_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "regimen_fiscal" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "codigo" varchar(10) NOT NULL UNIQUE, "descripcion" varchar(200) NOT NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "clientes" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "razon_social" varchar(200) NOT NULL, "codigo_postal" varchar(5) NOT NULL, "rfc" varchar(13) NOT NULL UNIQUE, "domicilio" text NOT NULL, "telefono" varchar(15) NOT NULL, "email_principal" varchar(254) NOT NULL, "email_alterno" varchar(254) NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "regimen_fiscal_id" bigint NOT NULL REFERENCES "regimen_fiscal" ("id") DEFERRABLE INITIALLY DEFERRED, "ciudad" varchar(100) NULL, "direccion_entrega" text NULL, "estado" varchar(100) NULL, "numero_bodega" varchar(50) NULL, "telefono_bodega" varchar(15) NULL);
CREATE INDEX "clientes_usuario_creacion_id_98518245" ON "clientes" ("usuario_creacion_id");
CREATE INDEX "clientes_usuario_modificacion_id_2eb31006" ON "clientes" ("usuario_modificacion_id");
CREATE INDEX "clientes_regimen_fiscal_id_c2575dc7" ON "clientes" ("regimen_fiscal_id");
CREATE INDEX "clientes_rfc_48375a_idx" ON "clientes" ("rfc");
CREATE INDEX "clientes_razon_s_6d1478_idx" ON "clientes" ("razon_social");
CREATE INDEX "clientes_activo_1f6d14_idx" ON "clientes" ("activo");
CREATE TABLE IF NOT EXISTS "proveedores" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(200) NOT NULL, "rfc" varchar(13) NOT NULL UNIQUE, "domicilio" text NOT NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "proveedores_usuario_creacion_id_b2f0a788" ON "proveedores" ("usuario_creacion_id");
CREATE INDEX "proveedores_usuario_modificacion_id_dce59724" ON "proveedores" ("usuario_modificacion_id");
CREATE INDEX "proveedores_rfc_669982_idx" ON "proveedores" ("rfc");
CREATE INDEX "proveedores_nombre_4e7949_idx" ON "proveedores" ("nombre");
CREATE INDEX "proveedores_activo_068092_idx" ON "proveedores" ("activo");
CREATE TABLE IF NOT EXISTS "transportistas" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre_completo" varchar(200) NOT NULL, "licencia" varchar(50) NOT NULL, "domicilio" text NOT NULL, "telefono" varchar(15) NOT NULL, "tipo_camion" varchar(100) NOT NULL, "placas_unidad" varchar(20) NOT NULL, "placas_remolque" varchar(20) NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "transportistas_usuario_creacion_id_1bd60eb8" ON "transportistas" ("usuario_creacion_id");
CREATE INDEX "transportistas_usuario_modificacion_id_e72d030e" ON "transportistas" ("usuario_modificacion_id");
CREATE INDEX "transportis_licenci_0fe8ad_idx" ON "transportistas" ("licencia");
CREATE INDEX "transportis_nombre__130c80_idx" ON "transportistas" ("nombre_completo");
CREATE INDEX "transportis_placas__61e3be_idx" ON "transportistas" ("placas_unidad");
CREATE INDEX "transportis_activo_f2c8fb_idx" ON "transportistas" ("activo");
CREATE TABLE IF NOT EXISTS "lotes_origen" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(200) NOT NULL, "observaciones" text NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "lotes_origen_usuario_creacion_id_628f24fd" ON "lotes_origen" ("usuario_creacion_id");
CREATE INDEX "lotes_origen_usuario_modificacion_id_1ec68572" ON "lotes_origen" ("usuario_modificacion_id");
CREATE INDEX "lotes_orige_nombre_8131b3_idx" ON "lotes_origen" ("nombre");
CREATE INDEX "lotes_orige_activo_ad30f3_idx" ON "lotes_origen" ("activo");
CREATE TABLE IF NOT EXISTS "clasificaciones_gasto" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "descripcion" varchar(200) NOT NULL, "observaciones" text NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "clasificaciones_gasto_usuario_creacion_id_acb74aec" ON "clasificaciones_gasto" ("usuario_creacion_id");
CREATE INDEX "clasificaciones_gasto_usuario_modificacion_id_1a8365f8" ON "clasificaciones_gasto" ("usuario_modificacion_id");
CREATE INDEX "clasificaci_descrip_e92818_idx" ON "clasificaciones_gasto" ("descripcion");
CREATE INDEX "clasificaci_activo_4e8b21_idx" ON "clasificaciones_gasto" ("activo");
CREATE TABLE IF NOT EXISTS "centros_costo" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "descripcion" varchar(200) NOT NULL, "hectareas" decimal NOT NULL, "observaciones" text NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "centros_costo_usuario_creacion_id_76d8ff6d" ON "centros_costo" ("usuario_creacion_id");
CREATE INDEX "centros_costo_usuario_modificacion_id_b23238ef" ON "centros_costo" ("usuario_modificacion_id");
CREATE INDEX "centros_cos_descrip_3af6a8_idx" ON "centros_costo" ("descripcion");
CREATE INDEX "centros_cos_activo_4ca146_idx" ON "centros_costo" ("activo");
CREATE TABLE IF NOT EXISTS "productos_servicios" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sku" varchar(50) NOT NULL UNIQUE, "descripcion" varchar(200) NOT NULL, "producto_servicio" bool NOT NULL, "clave_sat" varchar(20) NOT NULL, "impuesto" varchar(20) NOT NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "unidad_medida" varchar(50) NOT NULL, impuesto_catalogo_id INTEGER REFERENCES tipo_impuesto(id));
CREATE INDEX "productos_servicios_usuario_creacion_id_48b2f889" ON "productos_servicios" ("usuario_creacion_id");
CREATE INDEX "productos_servicios_usuario_modificacion_id_d295b259" ON "productos_servicios" ("usuario_modificacion_id");
CREATE INDEX "productos_s_sku_ddc93a_idx" ON "productos_servicios" ("sku");
CREATE INDEX "productos_s_descrip_3d9234_idx" ON "productos_servicios" ("descripcion");
CREATE INDEX "productos_s_product_fa5ceb_idx" ON "productos_servicios" ("producto_servicio");
CREATE INDEX "productos_s_clave_s_83ebe6_idx" ON "productos_servicios" ("clave_sat");
CREATE INDEX "productos_s_activo_d0202b_idx" ON "productos_servicios" ("activo");
CREATE TABLE IF NOT EXISTS "cultivos" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "variedad" varchar(100) NOT NULL, "observaciones" text NOT NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cultivos_usuario_creacion_id_78ddb04d" ON "cultivos" ("usuario_creacion_id");
CREATE INDEX "cultivos_usuario_modificacion_id_33627fb7" ON "cultivos" ("usuario_modificacion_id");
CREATE TABLE IF NOT EXISTS "remisiones_detalles" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "calidad" varchar(20) NOT NULL, "no_arps" integer unsigned NOT NULL CHECK ("no_arps" >= 0), "kgs_enviados" decimal NOT NULL, "merma_arps" integer unsigned NOT NULL CHECK ("merma_arps" >= 0), "kgs_liquidados" decimal NOT NULL, "kgs_merma" decimal NOT NULL, "precio" decimal NOT NULL, "importe_liquidado" decimal NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "cultivo_id" integer NOT NULL REFERENCES "cultivos" ("codigo") DEFERRABLE INITIALLY DEFERRED, "remision_id" integer NOT NULL REFERENCES "remisiones" ("codigo") DEFERRABLE INITIALLY DEFERRED, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "peso_promedio" decimal NOT NULL, "fecha_liquidacion" datetime NULL, "usuario_liquidacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "remisiones_detalles_cultivo_id_33c521c0" ON "remisiones_detalles" ("cultivo_id");
CREATE INDEX "remisiones_detalles_remision_id_81947758" ON "remisiones_detalles" ("remision_id");
CREATE INDEX "remisiones_detalles_usuario_creacion_id_f63ae257" ON "remisiones_detalles" ("usuario_creacion_id");
CREATE INDEX "remisiones_detalles_usuario_modificacion_id_2c8550c5" ON "remisiones_detalles" ("usuario_modificacion_id");
CREATE INDEX "remisiones__remisio_a66c5b_idx" ON "remisiones_detalles" ("remision_id");
CREATE INDEX "remisiones__cultivo_637993_idx" ON "remisiones_detalles" ("cultivo_id");
CREATE INDEX "remisiones__calidad_f9c377_idx" ON "remisiones_detalles" ("calidad");
CREATE INDEX "remisiones_detalles_usuario_liquidacion_id_975722f1" ON "remisiones_detalles" ("usuario_liquidacion_id");
CREATE TABLE IF NOT EXISTS "remisiones" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ciclo" varchar(100) NOT NULL, "folio" integer unsigned NOT NULL CHECK ("folio" >= 0), "fecha" date NOT NULL, "costo_flete" decimal NOT NULL, "observaciones" text NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "cliente_id" integer NOT NULL REFERENCES "clientes" ("codigo") DEFERRABLE INITIALLY DEFERRED, "lote_origen_id" integer NOT NULL REFERENCES "lotes_origen" ("codigo") DEFERRABLE INITIALLY DEFERRED, "transportista_id" integer NOT NULL REFERENCES "transportistas" ("codigo") DEFERRABLE INITIALLY DEFERRED, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "cancelada" bool NOT NULL, "fecha_cancelacion" datetime NULL, "folio_sustituto" varchar(50) NULL, "motivo_cancelacion" text NULL, "usuario_cancelacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "facturado" bool NOT NULL, "pagado" bool NOT NULL, "fecha_pago" date NULL);
CREATE UNIQUE INDEX "remisiones_ciclo_folio_3d4e7043_uniq" ON "remisiones" ("ciclo", "folio");
CREATE INDEX "remisiones_cliente_id_49ff0ed3" ON "remisiones" ("cliente_id");
CREATE INDEX "remisiones_lote_origen_id_0188814c" ON "remisiones" ("lote_origen_id");
CREATE INDEX "remisiones_transportista_id_cf95ad50" ON "remisiones" ("transportista_id");
CREATE INDEX "remisiones_usuario_creacion_id_5c8658f8" ON "remisiones" ("usuario_creacion_id");
CREATE INDEX "remisiones_usuario_modificacion_id_883613da" ON "remisiones" ("usuario_modificacion_id");
CREATE INDEX "remisiones_usuario_cancelacion_id_412b2e0a" ON "remisiones" ("usuario_cancelacion_id");
CREATE INDEX "remisiones_ciclo_d6b184_idx" ON "remisiones" ("ciclo", "folio");
CREATE INDEX "remisiones_fecha_697658_idx" ON "remisiones" ("fecha");
CREATE INDEX "remisiones_cliente_eb1548_idx" ON "remisiones" ("cliente_id");
CREATE INDEX "remisiones_lote_or_a06442_idx" ON "remisiones" ("lote_origen_id");
CREATE INDEX "remisiones_transpo_0f0fb8_idx" ON "remisiones" ("transportista_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "cuentas_bancarias" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre_banco" varchar(200) NOT NULL, "numero_cuenta" varchar(50) NOT NULL, "nombre_corto" varchar(100) NOT NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cuentas_bancarias_usuario_creacion_id_38696ed7" ON "cuentas_bancarias" ("usuario_creacion_id");
CREATE INDEX "cuentas_bancarias_usuario_modificacion_id_16485e2d" ON "cuentas_bancarias" ("usuario_modificacion_id");
CREATE INDEX "cuentas_ban_nombre__304a88_idx" ON "cuentas_bancarias" ("nombre_banco");
CREATE INDEX "cuentas_ban_numero__a7969b_idx" ON "cuentas_bancarias" ("numero_cuenta");
CREATE INDEX "cuentas_ban_nombre__013077_idx" ON "cuentas_bancarias" ("nombre_corto");
CREATE INDEX "cuentas_ban_activo_baed7f_idx" ON "cuentas_bancarias" ("activo");
CREATE TABLE IF NOT EXISTS "core_pagoremision" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "metodo_pago" varchar(20) NOT NULL, "monto" decimal NOT NULL, "fecha_pago" date NOT NULL, "referencia" varchar(100) NULL, "observaciones" text NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "remision_id" integer NOT NULL REFERENCES "remisiones" ("codigo") DEFERRABLE INITIALLY DEFERRED, "usuario_creacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "cuenta_bancaria_id" integer NULL REFERENCES "cuentas_bancarias" ("codigo") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "core_pagoremision_remision_id_22ebabb1" ON "core_pagoremision" ("remision_id");
CREATE INDEX "core_pagoremision_usuario_creacion_id_821e3d02" ON "core_pagoremision" ("usuario_creacion_id");
CREATE INDEX "core_pagoremision_usuario_modificacion_id_b0ba4c13" ON "core_pagoremision" ("usuario_modificacion_id");
CREATE INDEX "core_pagoremision_cuenta_bancaria_id_59dcd387" ON "core_pagoremision" ("cuenta_bancaria_id");
CREATE TABLE IF NOT EXISTS "presupuestos_gasto" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ciclo" varchar(100) NOT NULL, "importe" decimal NOT NULL, "observaciones" text NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "centro_costo_id" integer NOT NULL REFERENCES "centros_costo" ("codigo") DEFERRABLE INITIALLY DEFERRED, "clasificacion_gasto_id" integer NOT NULL REFERENCES "clasificaciones_gasto" ("codigo") DEFERRABLE INITIALLY DEFERRED, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "presupuestos_gasto_centro_costo_id_clasificacion_gasto_id_ciclo_d70d973d_uniq" ON "presupuestos_gasto" ("centro_costo_id", "clasificacion_gasto_id", "ciclo");
CREATE INDEX "presupuestos_gasto_centro_costo_id_ca2a95ce" ON "presupuestos_gasto" ("centro_costo_id");
CREATE INDEX "presupuestos_gasto_clasificacion_gasto_id_37996f00" ON "presupuestos_gasto" ("clasificacion_gasto_id");
CREATE INDEX "presupuestos_gasto_usuario_creacion_id_ac4a1629" ON "presupuestos_gasto" ("usuario_creacion_id");
CREATE INDEX "presupuestos_gasto_usuario_modificacion_id_521c6881" ON "presupuestos_gasto" ("usuario_modificacion_id");
CREATE INDEX "presupuesto_centro__80c89d_idx" ON "presupuestos_gasto" ("centro_costo_id", "ciclo");
CREATE INDEX "presupuesto_ciclo_1f3f8d_idx" ON "presupuestos_gasto" ("ciclo");
CREATE INDEX "presupuesto_activo_5a4c84_idx" ON "presupuestos_gasto" ("activo");
CREATE TABLE IF NOT EXISTS "presupuestos" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ciclo" varchar(100) NOT NULL, "observaciones" text NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "centro_costo_id" integer NOT NULL REFERENCES "centros_costo" ("codigo") DEFERRABLE INITIALLY DEFERRED, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "presupuesto_detalles" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "importe" decimal NOT NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "clasificacion_gasto_id" integer NOT NULL REFERENCES "clasificaciones_gasto" ("codigo") DEFERRABLE INITIALLY DEFERRED, "presupuesto_id" integer NOT NULL REFERENCES "presupuestos" ("codigo") DEFERRABLE INITIALLY DEFERRED, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "presupuesto_centro__b3ca24_idx" ON "presupuestos" ("centro_costo_id", "ciclo");
CREATE INDEX "presupuesto_ciclo_178382_idx" ON "presupuestos" ("ciclo");
CREATE INDEX "presupuesto_activo_888055_idx" ON "presupuestos" ("activo");
CREATE UNIQUE INDEX "presupuestos_centro_costo_id_ciclo_ddefd2e1_uniq" ON "presupuestos" ("centro_costo_id", "ciclo");
CREATE INDEX "presupuesto_presupu_1b9751_idx" ON "presupuesto_detalles" ("presupuesto_id");
CREATE INDEX "presupuesto_clasifi_f37f99_idx" ON "presupuesto_detalles" ("clasificacion_gasto_id");
CREATE INDEX "presupuesto_activo_4a5ee0_idx" ON "presupuesto_detalles" ("activo");
CREATE UNIQUE INDEX "presupuesto_detalles_presupuesto_id_clasificacion_gasto_id_acd12eb2_uniq" ON "presupuesto_detalles" ("presupuesto_id", "clasificacion_gasto_id");
CREATE INDEX "presupuestos_centro_costo_id_ffbabb1c" ON "presupuestos" ("centro_costo_id");
CREATE INDEX "presupuestos_usuario_creacion_id_0705ce24" ON "presupuestos" ("usuario_creacion_id");
CREATE INDEX "presupuestos_usuario_modificacion_id_9e68dab9" ON "presupuestos" ("usuario_modificacion_id");
CREATE INDEX "presupuesto_detalles_clasificacion_gasto_id_095aa86d" ON "presupuesto_detalles" ("clasificacion_gasto_id");
CREATE INDEX "presupuesto_detalles_presupuesto_id_58485313" ON "presupuesto_detalles" ("presupuesto_id");
CREATE INDEX "presupuesto_detalles_usuario_creacion_id_8bbb062c" ON "presupuesto_detalles" ("usuario_creacion_id");
CREATE INDEX "presupuesto_detalles_usuario_modificacion_id_dbe6a4a3" ON "presupuesto_detalles" ("usuario_modificacion_id");
CREATE TABLE IF NOT EXISTS "gastos" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ciclo" varchar(10) NOT NULL, "fecha_gasto" date NOT NULL, "observaciones" text NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "presupuesto_id" integer NOT NULL REFERENCES "presupuestos" ("codigo") DEFERRABLE INITIALLY DEFERRED, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "gasto_detalles" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "factura" varchar(100) NOT NULL, "concepto" varchar(255) NOT NULL, "importe" decimal NOT NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "clasificacion_gasto_id" integer NOT NULL REFERENCES "clasificaciones_gasto" ("codigo") DEFERRABLE INITIALLY DEFERRED, "gasto_id" integer NOT NULL REFERENCES "gastos" ("codigo") DEFERRABLE INITIALLY DEFERRED, "proveedor_id" integer NOT NULL REFERENCES "proveedores" ("codigo") DEFERRABLE INITIALLY DEFERRED, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "gastos_presupu_5346b6_idx" ON "gastos" ("presupuesto_id", "ciclo");
CREATE INDEX "gastos_fecha_g_cb5346_idx" ON "gastos" ("fecha_gasto");
CREATE INDEX "gastos_activo_42870b_idx" ON "gastos" ("activo");
CREATE INDEX "gasto_detal_gasto_i_0fa69d_idx" ON "gasto_detalles" ("gasto_id");
CREATE INDEX "gasto_detal_proveed_4e6c40_idx" ON "gasto_detalles" ("proveedor_id");
CREATE INDEX "gasto_detal_factura_91c7fd_idx" ON "gasto_detalles" ("factura");
CREATE INDEX "gasto_detal_activo_c380e1_idx" ON "gasto_detalles" ("activo");
CREATE INDEX "gastos_presupuesto_id_58ac37f5" ON "gastos" ("presupuesto_id");
CREATE INDEX "gastos_usuario_creacion_id_395d7110" ON "gastos" ("usuario_creacion_id");
CREATE INDEX "gastos_usuario_modificacion_id_3d2d4a4a" ON "gastos" ("usuario_modificacion_id");
CREATE INDEX "gasto_detalles_clasificacion_gasto_id_125305ff" ON "gasto_detalles" ("clasificacion_gasto_id");
CREATE INDEX "gasto_detalles_gasto_id_755f955e" ON "gasto_detalles" ("gasto_id");
CREATE INDEX "gasto_detalles_proveedor_id_ea7db568" ON "gasto_detalles" ("proveedor_id");
CREATE INDEX "gasto_detalles_usuario_creacion_id_496a05ed" ON "gasto_detalles" ("usuario_creacion_id");
CREATE INDEX "gasto_detalles_usuario_modificacion_id_7db26009" ON "gasto_detalles" ("usuario_modificacion_id");
CREATE TABLE IF NOT EXISTS "configuracion_sistema" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ciclo_actual" varchar(100) NOT NULL, "nombre_pac" varchar(50) NOT NULL, "contrato" varchar(100) NOT NULL, "usuario_pac" varchar(100) NOT NULL, "password_pac" varchar(100) NOT NULL, "certificado" text NULL, "llave" text NULL, "password_llave" varchar(100) NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "certificado_nombre" varchar(255) NULL, "llave_nombre" varchar(255) NULL, "direccion" text NOT NULL, "razon_social" varchar(200) NOT NULL, "rfc" varchar(13) NOT NULL, "telefono" varchar(15) NOT NULL, "logo_empresa" varchar(100) NULL, "ultima_actualizacion_catalogos" datetime NULL);
CREATE INDEX "configuracion_sistema_usuario_creacion_id_036a41e4" ON "configuracion_sistema" ("usuario_creacion_id");
CREATE INDEX "configuracion_sistema_usuario_modificacion_id_70b69eb5" ON "configuracion_sistema" ("usuario_modificacion_id");
CREATE TABLE IF NOT EXISTS "emisores" ("codigo" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "razon_social" varchar(200) NOT NULL, "rfc" varchar(13) NOT NULL, "codigo_postal" varchar(5) NOT NULL, "archivo_certificado" text NULL, "password_llave" varchar(100) NOT NULL, "activo" bool NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "contrato" varchar(100) NOT NULL, "nombre_pac" varchar(50) NOT NULL, "password_pac" varchar(100) NOT NULL, "usuario_pac" varchar(100) NOT NULL, "timbrado_prueba" bool NOT NULL, "regimen_fiscal" varchar(3) NOT NULL, "serie" varchar(10) NOT NULL, "archivo_llave" text NULL, "nombre_archivo_certificado" varchar(255) NULL, "nombre_archivo_llave" varchar(255) NULL);
CREATE INDEX "emisores_usuario_creacion_id_f7ffe3c1" ON "emisores" ("usuario_creacion_id");
CREATE INDEX "emisores_usuario_modificacion_id_e78f7c63" ON "emisores" ("usuario_modificacion_id");
CREATE INDEX "emisores_rfc_8659b0_idx" ON "emisores" ("rfc");
CREATE INDEX "emisores_razon_s_d5d49d_idx" ON "emisores" ("razon_social");
CREATE INDEX "emisores_activo_209d53_idx" ON "emisores" ("activo");
CREATE TABLE IF NOT EXISTS "factura_detalles" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "no_identificacion" varchar(50) NULL, "concepto" varchar(1000) NOT NULL, "precio" decimal NOT NULL, "clave_prod_serv" varchar(20) NOT NULL, "unidad" varchar(20) NOT NULL, "objeto_impuesto" varchar(2) NOT NULL, "importe" decimal NOT NULL, "impuesto_concepto" decimal NOT NULL, "factura_id" integer NOT NULL REFERENCES "facturas" ("folio") DEFERRABLE INITIALLY DEFERRED, "producto_servicio_id" integer NOT NULL REFERENCES "productos_servicios" ("codigo") DEFERRABLE INITIALLY DEFERRED, "clave_unidad" varchar(3) NOT NULL, "descuento" decimal NULL, "cantidad" decimal NOT NULL);
CREATE INDEX "factura_detalles_factura_id_af533a30" ON "factura_detalles" ("factura_id");
CREATE INDEX "factura_detalles_producto_servicio_id_b57142f2" ON "factura_detalles" ("producto_servicio_id");
CREATE INDEX "factura_det_factura_81d21b_idx" ON "factura_detalles" ("factura_id");
CREATE INDEX "factura_det_clave_p_b2a196_idx" ON "factura_detalles" ("clave_prod_serv");
CREATE INDEX "factura_det_objeto__f48559_idx" ON "factura_detalles" ("objeto_impuesto");
CREATE TABLE IF NOT EXISTS "facturas" ("serie" varchar(25) NULL, "folio" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "fecha_emision" datetime NOT NULL, "lugar_expedicion" varchar(5) NOT NULL, "exportacion" varchar(2) NOT NULL, "metodo_pago" varchar(3) NOT NULL, "moneda" varchar(3) NOT NULL, "forma_pago" varchar(2) NOT NULL, "tipo_cambio" decimal NOT NULL, "subtotal" decimal NOT NULL, "impuesto" decimal NOT NULL, "total" decimal NOT NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "emisor_id" integer NOT NULL REFERENCES "emisores" ("codigo") DEFERRABLE INITIALLY DEFERRED, "receptor_id" integer NOT NULL REFERENCES "clientes" ("codigo") DEFERRABLE INITIALLY DEFERRED, "usuario_creacion_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_modificacion_id" bigint NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "cancelada" bool NOT NULL, "acuse_cancelacion" text NULL, "errores_validacion" text NULL, "estado_timbrado" varchar(20) NOT NULL, "fecha_cancelacion" datetime NULL, "fecha_timbrado" datetime NULL, "intentos_timbrado" integer unsigned NOT NULL CHECK ("intentos_timbrado" >= 0), "motivo_cancelacion" varchar(500) NULL, "no_cert_sat" varchar(20) NULL, "sello_sat" text NULL, "ultimo_intento" datetime NULL, "uuid" varchar(36) NULL, "xml_original" text NULL, "xml_timbrado" text NULL, "certificado" text NULL, "confirmacion" varchar(2) NULL, "descuento" decimal NULL, "no_certificado" varchar(20) NULL, "sello" text NULL, "tipo_comprobante" varchar(1) NOT NULL, "uso_cfdi" varchar(5) NOT NULL, "año_informacion_global" integer NULL, "meses" varchar(2) NULL, "periodicidad" varchar(2) NULL, "codigo_qr" text NULL, "cadena_original_sat" text NULL);
CREATE UNIQUE INDEX "facturas_serie_folio_3362d0d4_uniq" ON "facturas" ("serie", "folio");
CREATE INDEX "facturas_emisor_id_3efb8fb1" ON "facturas" ("emisor_id");
CREATE INDEX "facturas_receptor_id_cbe15469" ON "facturas" ("receptor_id");
CREATE INDEX "facturas_usuario_creacion_id_a67ce2a8" ON "facturas" ("usuario_creacion_id");
CREATE INDEX "facturas_usuario_modificacion_id_7dbb4a78" ON "facturas" ("usuario_modificacion_id");
CREATE INDEX "facturas_serie_583a53_idx" ON "facturas" ("serie", "folio");
CREATE INDEX "facturas_fecha_e_2669a7_idx" ON "facturas" ("fecha_emision");
CREATE INDEX "facturas_emisor__a4b343_idx" ON "facturas" ("emisor_id");
CREATE INDEX "facturas_recepto_d098e8_idx" ON "facturas" ("receptor_id");
CREATE INDEX "facturas_uuid_a5ed0b_idx" ON "facturas" ("uuid");
CREATE INDEX "facturas_estado__7cb2cc_idx" ON "facturas" ("estado_timbrado");
CREATE INDEX "facturas_fecha_t_b595d3_idx" ON "facturas" ("fecha_timbrado");
CREATE INDEX "facturas_cancela_f63b14_idx" ON "facturas" ("cancelada");
CREATE INDEX "facturas_tipo_co_fe100c_idx" ON "facturas" ("tipo_comprobante");
CREATE INDEX "facturas_exporta_a41794_idx" ON "facturas" ("exportacion");
CREATE TABLE IF NOT EXISTS "pagos_factura" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "fecha_pago" datetime NOT NULL, "monto_pago" decimal NOT NULL, "tipo_pago" varchar(10) NOT NULL, "referencia_pago" varchar(100) NULL, "observaciones" text NULL, "fecha_creacion" datetime NOT NULL, "fecha_modificacion" datetime NOT NULL, "factura_id" integer NOT NULL REFERENCES "facturas" ("folio") DEFERRABLE INITIALLY DEFERRED, "usuario_registro_id" bigint NOT NULL REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED, "fecha_timbrado" varchar(50) NULL, "no_certificado_sat" varchar(20) NULL, "sello" text NULL, "sello_sat" text NULL, "uuid" varchar(36) NULL, "xml_timbrado" text NULL, "num_parcialidad" integer unsigned NOT NULL CHECK ("num_parcialidad" >= 0), "forma_pago" varchar(2) NOT NULL, "cadena_original_sat" text NULL, "codigo_qr" text NULL);
CREATE INDEX "pagos_factura_factura_id_04ad2184" ON "pagos_factura" ("factura_id");
CREATE INDEX "pagos_factura_usuario_registro_id_0b026e49" ON "pagos_factura" ("usuario_registro_id");
CREATE TABLE tipo_impuesto (id INTEGER PRIMARY KEY AUTOINCREMENT, codigo varchar(3) NOT NULL, nombre varchar(100) NOT NULL, tasa decimal(6,4) NOT NULL, activo bool DEFAULT 1, fecha_creacion datetime DEFAULT CURRENT_TIMESTAMP, fecha_modificacion datetime DEFAULT CURRENT_TIMESTAMP);
