name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python manage.py check --settings=directiva_agricola.settings_simple
        python manage.py test --settings=directiva_agricola.settings_simple
        
    - name: Deploy to EC2
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Actualizar código
          cd /tmp
          rm -rf directiva-agricola
          git clone https://github.com/${{ github.repository }}.git directiva-agricola
          
          # Detener servicios
          sudo systemctl stop directiva
          
          # Actualizar archivos
          sudo cp -r /tmp/directiva-agricola/* /opt/directiva-agricola/
          sudo chown -R directiva:directiva /opt/directiva-agricola/
          
          # Instalar dependencias
          cd /opt/directiva-agricola
          sudo pip3 install -r requirements.txt
          
          # Ejecutar migraciones
          sudo -u directiva RDS_HOSTNAME=${{ secrets.RDS_HOSTNAME }} \
            RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
            RDS_ADMIN_DB_NAME=${{ secrets.RDS_ADMIN_DB_NAME }} \
            RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            RDS_PORT=${{ secrets.RDS_PORT }} \
            python3 manage.py migrate --settings=directiva_agricola.settings_simple
            
          # Ejecutar migraciones para base de administración
          sudo -u directiva RDS_HOSTNAME=${{ secrets.RDS_HOSTNAME }} \
            RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
            RDS_ADMIN_DB_NAME=${{ secrets.RDS_ADMIN_DB_NAME }} \
            RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            RDS_PORT=${{ secrets.RDS_PORT }} \
            python3 manage.py migrate --database=administracion --settings=directiva_agricola.settings_simple
          
          # Recopilar archivos estáticos
          sudo -u directiva python3 manage.py collectstatic --noinput --settings=directiva_agricola.settings_simple
          
          # Reiniciar servicios
          sudo systemctl start directiva
          sudo systemctl reload nginx
          
          # Verificar estado
          sudo systemctl status directiva
          sudo systemctl status nginx
